// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "index",
    "release_notes",
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index' },
      items: [
        'getting-started/download',
        'getting-started/installing',
        'getting-started/examples',
      ],
    },
    {
      type: 'category',
      label: 'How-to',
      link: { type: 'generated-index' },
      items: [
        'how-to/create_update',
        'how-to/read_data',
        'how-to/insert_csv',
        'how-to/insert_delete',
        'how-to/sql_commands',
        'how-to/publish',
        'how-to/geodata',
        'how-to/defrag',
      ],
    },
    {
      type: 'category',
      label: 'SQL',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'category',
          label: 'Statements',
          link: { type: 'generated-index' },
          items: [
            {type: 'autogenerated', dirName: 'sql/statement'}
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          link: { type: 'generated-index' },
          items: [
            {type: 'autogenerated', dirName: 'sql/func'}
          ],
        },
        {
          type: 'category',
          label: 'Data types',
          link: { type: 'generated-index' },
          items: [
            {type: 'autogenerated', dirName: 'sql/datatype'}
          ],
        },
        {
          type: 'category',
          label: 'External formats',
          link: { type: 'generated-index' },
          items: [
            "sql/external/index",
            "sql/external/syntax",
            "sql/external/formats"
          ],
        },
        "sql/process_settings",
        "sql/connection_settings",
        "sql/fragment_sourcelocation",
      ],
    },
    "client_languages",
    "faq",
  ],
};

module.exports = sidebars;
