// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "index",
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index' },
      items: [
        'getting-started/download',
        'getting-started/installing',
        'getting-started/examples',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'generated-index' },
      items: [
        'guides/create_update',
        'guides/read_data',
        'guides/insert_csv',
        'guides/insert_delete',
        'guides/sql_commands',
        'guides/publish',
        'guides/geodata',
        'guides/defrag',
      ],
    },
    {
      type: 'category',
      label: 'The client library',
      link: { type: 'doc', id: 'client-lib/index' },
      items: [
        {
          type: 'category',
          label: 'Starting a Hyper process',
          link: { type: 'doc', id: 'client-lib/process' },
          items: [ 'client-lib/process_settings' ],
        },
        {
          type: 'category',
          label: 'Connecting with a Hyper database',
          link: { type: 'doc', id: 'client-lib/connection' },
          items: [ 'client-lib/connection_settings' ],
        },
        'client-lib/sql-execution',
        'client-lib/sql-formatting',
        'client-lib/meta-queries',
        'client-lib/ddl-utils',
        'client-lib/inserter',
      ],
    },
    {
      type: 'category',
      label: 'SQL',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'category',
          label: 'Statements',
          link: { type: 'generated-index' },
          items: [
            {type: 'autogenerated', dirName: 'sql/statement'}
          ],
        },
        {
          type: 'category',
          label: 'Data Types',
          link: { type: 'doc', id: 'sql/datatype/index' },
          items: [
            "sql/datatype/binary",
            "sql/datatype/boolean",
            "sql/datatype/character",
            "sql/datatype/datetime",
            "sql/datatype/numeric",
          ],
        },
        {
          type: 'category',
          label: 'Functions and Operators',
          link: { type: 'doc', id: 'sql/func/index' },
          items: [
            "sql/func/conversion",
            "sql/func/comparison",
            "sql/func/logical",
            "sql/func/conditional",
            "sql/func/string",
            "sql/func/matching",
            "sql/func/formatting",
            "sql/func/datetime",
            "sql/func/geography",
            "sql/func/aggregate",
            "sql/func/window",
            "sql/func/subquery",
            "sql/func/setreturning",
          ],
        },
        {
          type: 'category',
          label: 'External Formats',
          link: { type: 'doc', id: 'sql/external/index' },
          items: [
            "sql/external/syntax",
            "sql/external/formats",
            "sql/external/fragment_sourcelocation",
          ],
        }
      ],
    },
    "release_notes",
    "faq",
  ],
};

module.exports = sidebars;
